---
name: spring-music-demo

releases:
- name: spring-music
  version: 0.0.1
  sha1: 339fe42598be3197d5dd27c273a5c9cd6e5cd346
  url: https://github.com/aosta/spring-music-boshrelease/releases/download/v0.0.1/spring-music-0.0.1.tgz
- name: "garden-runc"
  version: "latest"

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: web
  jobs:
    - name: spring-music
      release: spring-music
  instances: 1
  stemcell: default
  azs:
    - z1
  vm_type: default
  persistent_disk_type: default
  networks:
  - name: default

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
